### ISSUE TITLE
symbol "-" breaks grammar

### ISSUE THREAD

**Issue by JohnFinn** [ngalaiko/tree-sitter-go-template#23]
This file has a broken syntax highlighting on the topmost key `foo:`
```yaml
foo:
  bar: {{ .Values.foo.bar }}-{{ .Values.foo.bar }}
```
and yields the following tree
![Screenshot from 2024-09-23 19-08-22](https://github.com/user-attachments/assets/15804f73-34eb-48fd-8d2d-0382d0c4f3e5)
when replacing "-" with "a" highlighting starts to work as expected and tree changes significantly
![Screenshot from 2024-09-23 19-08-14](https://github.com/user-attachments/assets/8ef20a69-23f1-481c-be09-62172ec072c1)

**Comment by IzhakJakov** [comment]
Thank you for opening this issue!

Here is another example:
```yaml
metadata:
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
```

```clojure
(template ; [0, 0] - [3, 0]
  (text ; [0, 0] - [1, 9]
    (ERROR ; [0, 0] - [1, 8]
      (flow_node ; [0, 0] - [0, 8]
        (plain_scalar ; [0, 0] - [0, 8]
          (string_scalar))) ; [0, 0] - [0, 8]
      (block_mapping_pair ; [1, 2] - [1, 8]
        key: (flow_node ; [1, 2] - [1, 7]
          (plain_scalar ; [1, 2] - [1, 7]
            (string_scalar)))))) ; [1, 2] - [1, 7]
  (selector_expression ; [1, 12] - [1, 23]
    operand: (field ; [1, 12] - [1, 18]
      name: (identifier)) ; [1, 13] - [1, 18]
    field: (field_identifier)) ; [1, 19] - [1, 23]
  (text) ; [1, 26] - [1, 27]
  (selector_expression ; [1, 30] - [1, 44]
    operand: (field ; [1, 30] - [1, 36]
      name: (identifier)) ; [1, 31] - [1, 36]
    field: (field_identifier)) ; [1, 37] - [1, 44]
  (text) ; [1, 47] - [2, 11]
  (selector_expression ; [2, 14] - [2, 27]
    operand: (field ; [2, 14] - [2, 22]
      name: (identifier)) ; [2, 15] - [2, 22]
    field: (field_identifier)) ; [2, 23] - [2, 27]
  (text)) ; [2, 30] - [3, 0]
```

___Intentionally text and not image for easy copasting___ ;)

**Comment by qvalentin** [comment]
Hi, this is not something that can be fixed by this parser, as the syntax highlighting that is breaking is the yaml highlighting.

The given example is converted to the following yaml:

```yaml
foo:
  bar:                      -                     

```

This is not valid yaml and the yaml parser will have an error.

I just opened a issue for the yaml tree-sitter parser: https://github.com/tree-sitter-grammars/tree-sitter-yaml/issues/12

One possible workaround would be to use quotes in the example:

```yaml
foo:
  bar: "{{ .Values.foo.bar }}-{{ .Values.foo.bar }}"
```

**Comment by JohnFinn** [comment]
> Hi, this is not something that can be fixed by this parser, as the syntax highlighting that is breaking is the yaml highlighting.
> 
> The given example is converted to the following yaml:
> 
> ```yaml
> foo:
>   bar:                      -                     
> ```
> 
> This is not valid yaml and the yaml parser will have an error.

Then why an invalid yaml is being produced somewhere in the first place?

**Comment by qvalentin** [comment]
> Then why an invalid yaml is being produced somewhere in the first place?

That's how injections work, the go-template grammar only parses things inside {{ }}, everything else is then parsed by the yaml grammar.

See https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection for more info,
