### ISSUE TITLE
Current situation of forks

### ISSUE THREAD

**Issue by qvalentin** [ngalaiko/tree-sitter-go-template#6]
Hello everyone,
I would like to open the discussion on the current state of forks of this project. I have seen that several people are actively working on their forks, and want to suggest that we merge the changes to get the best possible grammar. Either we should look to get merge rights for this repo, or pick a fork that we all contribute to.

Also the fixes discussed in https://github.com/ngalaiko/tree-sitter-go-template/issues/3 were never upstreamed.

I'm very interested in creating a bug-free grammar, as I'm using the grammar for [helm-ls](https://github.com/mrjosh/helm-ls/), currently I'm trying to fix some bugs related to `if-else`: https://github.com/ngalaiko/tree-sitter-go-template/pull/5.

What is you opinion @msvechla, @baptman21, @Sephix?

**Comment by Sephix** [comment]
Hello,
I've forked the project to adapt it to the html/template package.
I have found that it ras not adapted to that, and I've heavily changed it
on my side, I've not pushed everything yet, and still have some issues.

**Comment by ngalaiko** [comment]
I am open to either archive this project, or give ownership to whomever is open to maintaining it

**Comment by ngalaiko** [comment]
@Sephix @qvalentin @baptman21 @msvechla - I've added you all as collaborators

**Comment by baptman21** [comment]
Thx @ngalaiko, personally I am open to work on this repo. In my case I am using helm quite frequently so I rely on this extension a lot.

**Comment by qvalentin** [comment]
Thank you @ngalaiko.

I would suggest we agreed on always having consent of two people before merging changes.
